title = "Rock Pereira's Data Page"
baseURL = "https://github.com/rockper/rockper.github.io"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
# themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 7 # originally 3. this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Modern Data Science"
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = "https://github.com/rockper"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/rock-pereira/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "/images/mount_rainier.jpg"
  recent_posts_number = 4
